[package]
name = "aws-console-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
aws-config = "0.56.1"
aws-sdk-s3 = "0.31.2"
aws-sdk-sts = "0.33.0"
better-panic = "0.3.0"
clap =  {version = "4.4.6", features = ["cargo", "string"]}
crossterm = "0.27.0"
directories = "5.0.1"
figment = { version = "0.10.11", features = ["toml"]}
libc = "0.2.149"
ratatui = "0.23.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"

[dev-dependencies]
assert_fs = "1.0.13"
